# -*- coding: utf-8 -*-
"""GENAI-3 AI placement bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YMpPWnPL-dKMX7TpWJWTV_6b6IoYsJ7a
"""

!kaggle datasets download -d aryan208/hr-interview-questions-and-ideal-answers

import os

file_size = os.path.getsize("/content/hr-interview-questions-and-ideal-answers.zip")
print("File size (MB):", file_size / (1024*1024))

!pip install transformers accelerate sentencepiece

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="google/flan-t5-base",
    max_length=512
)

def generate_response(prompt):
    response = generator(prompt, max_length=512, do_sample=True)[0]['generated_text']
    return response

import pandas as pd
import json
import random
import zipfile
import os
import ast

# -------------------------------
# 1. LOAD DATASETS
# -------------------------------

with open("/content/resume_dataset.json") as f:
    resume_data = json.load(f)
resume_df=pd.DataFrame(resume_data)
job_df = pd.read_csv("/content/indeed_job_dataset.csv")            # role, skills
course_df = pd.read_csv("/content/coursea_data.csv")      # course_name, skills


# Extract HR interview questions from the zip file
zip_file_path = "/content/hr-interview-questions-and-ideal-answers.zip"
extraction_path = "/content/hr_data"

# Create directory if it doesn't exist
os.makedirs(extraction_path, exist_ok=True)

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extraction_path)

# Load HR questions
hr_questions_file = os.path.join(extraction_path, "hr_interview_questions_dataset.json")
with open(hr_questions_file, "r") as f:
    hr_questions = json.load(f)

# ❌ ML Questions (CSV instead of JSON)
ml_df = pd.read_csv("/content/ml_interview_questions.csv")

# normalize column names
ml_df.columns = [col.lower() for col in ml_df.columns]

# convert to list of dict
ml_questions = ml_df.to_dict(orient="records")

print("Resume DataFrame (resume_df) head:")
display(resume_df.head())

print("Job DataFrame (job_df) head:")
display(job_df.head())

print("Course DataFrame (course_df) head:")
display(course_df.head())

print("ML DataFrame (ml_df) head:")
display(ml_df.head())

print("First 3 HR Questions (hr_questions):")
display(hr_questions[:3])

print("First 3 ML Questions (ml_questions):")
display(ml_questions[:3])

def clean_job_skills(job_df):
    job_df["Skill"] = job_df["Skill"].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else [])
    job_df["Skill"] = job_df["Skill"].apply(lambda x: [s.lower() for s in x])
    return job_df

job_df = clean_job_skills(job_df)

def build_skill_vocab(job_df):
    skills = set()
    for s in job_df["Skill"]:
        skills.update(s)
    return list(skills)

skill_vocab = build_skill_vocab(job_df)

def resume_analysis(resume_text, role):
    prompt = f"""
    You are an expert resume reviewer.

    Analyze this resume for the role of {role}.

    Evaluate:
    - Skills relevance
    - Project impact
    - ATS optimization

    Output:
    Score (0-100)
    Strengths
    Weaknesses
    Suggestions

    Resume:
    {resume_text}
    """
    return generate_response(prompt)

def extract_skills(resume_text):
    text = resume_text.lower()
    return list(set([skill for skill in skill_vocab if skill in text]))

def get_job_skills(role):
    filtered = job_df[job_df["Job_Title"].str.lower().str.contains(role.lower())]
    return filtered.iloc[0]["Skill"] if not filtered.empty else []

def skill_gap_prompt(user_skills, job_skills, role):
    prompt = f"""
    Compare candidate skills with job requirements.

    Role: {role}

    Candidate Skills:
    {user_skills}

    Required Skills:
    {job_skills}

    Output:
    Missing Skills
    Weak Areas
    Recommendations
    """
    return generate_response(prompt)

def recommend_courses(missing_skills):
    matched = course_df[
        course_df["course_title"].str.contains('|'.join(missing_skills), case=False, na=False)
    ]

    courses = matched["course_title"].head(5).tolist()

    prompt = f"""
    Recommend best courses for:
    {missing_skills}

    Available:
    {courses}

    Output:
    Course recommendations with reasons
    """
    return generate_response(prompt)

def generate_question(role):
    if role.lower() in ["hr", "manager"]:
        q = random.choice(hr_questions)
        return q["question"], q["ideal_answer"]
    else:
        q = random.choice(ml_questions)
        return q["question"], q["answer"]

def evaluate_answer(question, user_answer, ideal_answer):
    prompt = f"""
    Evaluate the answer.

    Question:
    {question}

    User Answer:
    {user_answer}

    Ideal Answer:
    {ideal_answer}

    Criteria:
    - Accuracy
    - Clarity
    - Completeness

    Output:
    Score (1-10)
    Strengths
    Weaknesses
    Improved Answer
    """
    return generate_response(prompt)

def learning_plan(missing_skills):
    prompt = f"""
    Create a 2-week study plan.

    Skills:
    {missing_skills}

    Think step-by-step.

    Output:
    Day-wise plan
    Tools
    Mini projects
    """
    return generate_response(prompt)

def full_pipeline(resume_text, role, user_answer):

    # Resume
    resume_result = resume_analysis(resume_text, role)

    # Skills
    user_skills = extract_skills(resume_text)
    job_skills = get_job_skills(role)

    # Gap
    gap = skill_gap_prompt(user_skills, job_skills, role)

    # Courses
    courses = recommend_courses(user_skills)

    # Learning plan
    plan = learning_plan(user_skills)

    # Interview
    question, ideal = generate_question(role)

    # Evaluation
    evaluation = evaluate_answer(question, user_answer, ideal)

    return {
        "resume_analysis": resume_result,
        "skills": user_skills,
        "skill_gap": gap,
        "courses": courses,
        "learning_plan": plan,
        "question": question,
        "ideal_answer": ideal,
        "evaluation": evaluation
    }

resume_text = resume_df.iloc[0]["text"]
role = "Data Scientist"
answer = "Machine learning is a method where models learn from data."

result = full_pipeline(resume_text, role, answer)

from pprint import pprint
pprint(result)

# ==============================
# INSTALL REQUIRED LIBRARIES
# ==============================
!pip install PyPDF2 python-docx transformers sentencepiece --quiet

# ==============================
# IMPORTS
# ==============================
import pandas as pd
import json, random, ast
from transformers import pipeline
from google.colab import files
import PyPDF2, docx

# ==============================
# LOAD MODEL
# ==============================
generator = pipeline("text-generation", model="google/flan-t5-base")

def generate_response(prompt):
    return generator(prompt, max_length=256)[0]['generated_text']

# ==============================
# SAMPLE DATA (Replace with your dataset if needed)
# ==============================
job_df = pd.DataFrame({
    "Job_Title": ["Data Scientist", "ML Engineer"],
    "Skill": [["python","machine learning","sql","deep learning"],
              ["python","pytorch","mlops","deep learning"]]
})

course_df = pd.DataFrame({
    "course_title": [
        "Machine Learning Basics",
        "Deep Learning with PyTorch",
        "SQL for Data Science",
        "MLOps Fundamentals"
    ]
})

ml_questions = [
    {"question": "What is overfitting?", "answer": "Model memorizes training data and fails to generalize."},
    {"question": "Explain gradient descent.", "answer": "Optimization algorithm to minimize loss."}
]

hr_questions = [
    {"question": "Tell me about yourself.", "ideal_answer": "Structured summary of background."}
]

# ==============================
# BUILD SKILL VOCAB
# ==============================
skill_vocab = list(set([s for sublist in job_df["Skill"] for s in sublist]))

# ==============================
# FILE UPLOAD (COLAB)
# ==============================
print("Upload your resume (PDF or DOCX)")
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# ==============================
# EXTRACT TEXT
# ==============================
def extract_text(file_name):
    text = ""
    if file_name.endswith(".pdf"):
        with open(file_name, "rb") as f:
            reader = PyPDF2.PdfReader(f)
            for page in reader.pages:
                text += page.extract_text() or ""
    elif file_name.endswith(".docx"):
        doc = docx.Document(file_name)
        text = "\n".join([p.text for p in doc.paragraphs])
    return text

resume_text = extract_text(file_name)

print("\n--- RESUME PREVIEW ---\n")
print(resume_text[:500])

# ==============================
# CORE FUNCTIONS
# ==============================
def extract_skills(text):
    text = text.lower()
    return list(set([s for s in skill_vocab if s in text]))

def get_job_skills(role):
    df = job_df[job_df["Job_Title"].str.lower().str.contains(role.lower())]
    return df.iloc[0]["Skill"] if not df.empty else []

def skill_gap(user_skills, job_skills, role):
    prompt = f"""
    Role: {role}
    Candidate Skills: {user_skills}
    Required Skills: {job_skills}

    Identify:
    Missing Skills
    Suggestions
    """
    return generate_response(prompt)

def recommend_courses(missing):
    prompt = f"""
    Suggest courses to learn:
    {missing}
    """
    return generate_response(prompt)

def get_question(role):
    if role.lower() == "hr":
        q = random.choice(hr_questions)
        return q["question"], q["ideal_answer"]
    else:
        q = random.choice(ml_questions)
        return q["question"], q["answer"]

def evaluate_answer(question, user_answer, ideal):
    prompt = f"""
    Question: {question}
    User Answer: {user_answer}
    Ideal Answer: {ideal}

    Give Score (1-10) and improvement
    """
    return generate_response(prompt)

# ==============================
# MAIN EXECUTION
# ==============================
role = input("\nEnter target role (e.g., Data Scientist): ")

# Skills
user_skills = extract_skills(resume_text)
job_skills = get_job_skills(role)
missing = list(set(job_skills) - set(user_skills))

print("\n--- SKILLS ---")
print("Your Skills:", user_skills)
print("Required Skills:", job_skills)

# Gap
print("\n--- SKILL GAP ANALYSIS ---")
print(skill_gap(user_skills, job_skills, role))

# Interview
print("\n--- INTERVIEW ---")
for i in range(2):
    q, ideal = get_question(role)
    print(f"\nQ{i+1}: {q}")
    ans = input("Your Answer: ")
    print("Feedback:", evaluate_answer(q, ans, ideal))

# Courses
print("\n--- COURSE RECOMMENDATIONS ---")
print(recommend_courses(missing))

